apiVersion: v1
kind: Service
metadata:
  name: weave-service
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: weave-gitops
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001