apiVersion: v1
kind: Service
metadata:
  name: ca-lan
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ca-lan
  namespace: kube-system
  labels:
    kubernetes.io/service-name: ca-lan
subsets:
  - addresses:
      - ip: 192.168.101.201
    ports:
      - name: https
        port: 443