apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-service
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  ports:
    - port: 9002
      targetPort: 8000 
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui-ingress
  namespace: longhorn-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - longhorn.syd.broc.ee
    secretName: longhorn-tls
  rules:
  - host: longhorn.syd.broc.ee
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-ui-service
            port:
              number: 9002