apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: networking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3050
      targetPort: 3050
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: adguard-service-1
  namespace: networking
  labels:
    kubernetes.io/service-name: adguard-service
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 3050
endpoints:
  - addresses: ["192.168.0.251"]
    conditions:
      ready: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-ingress-route
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.syd.broc.ee`)
      kind: Rule
      services:
        - name: adguard-service
          kind: Service
          port: 3050
  tls:
    secretName: adguard-tls