apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-cert
  namespace: networking
spec:
  secretName: adguard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - adguard.syd.broc.ee
