# Radarr Repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pree-helm-charts
  namespace: media
spec:
  interval: 1h
  url: https://pree.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-home-lab
  namespace: media
spec:
  interval: 1h
  url: https://k8s-home-lab.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 1h
  url: https://k8s-home-lab.github.io/helm-charts/