apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: lexfrei-charts
  namespace: media
spec:
  interval: 1h
  url: oci://ghcr.io/lexfrei/charts
  ref:
    semver: ">=0.0.0"