apiVersion: v1
kind: Service
metadata:
  name: plex-nodeport
  namespace: media
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
  ports:
    - name: http
      port: 32400
      targetPort: http
      protocol: TCP
      nodePort: 32400