apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paintman-ingress
  namespace: paintman
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - paintman.syd.broc.ee
    secretName: paintman-tls
  rules:
  - host: paintman.syd.broc.ee
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: paintman-frontend-service
            port:
              number: 5173