apiVersion: apps/v1
kind: Deployment
metadata:
  name: paintman-frontend-deployment
  namespace: paintman
  labels:
    app: paintman-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paintman-frontend
  template:
    metadata:
      labels:
        app: paintman-frontend
    spec:
      containers:
        - name: paintman-frontend
          image: ghcr.io/kiansajjadi/paintman-frontend:latest # {"$imagepolicy": "flux-system:paintman-frontend"}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "125Mi"
          ports:
            - containerPort: 80
              protocol: TCP

