apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolman-ingress
  namespace: spoolman
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - spoolman.syd.broc.ee
    secretName: spoolman-tls
  rules:
  - host: spoolman.syd.broc.ee
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: spoolman-service
            port:
              number: 7912
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spoolman-service
            port:
              number: 7912
---
# Added for mainsail 3d printer websocket requirement
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spoolman-ingress-route
  namespace: spoolman
spec:
  entryPoints:
    - websecure
  tls:
    secretName: spoolman-tls
  routes:
    - match: Host(`spoolman.syd.broc.ee`)
      kind: Rule
      services:
        - name: spoolman-service
          port: 7912