apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoolman-ingress
  namespace: spoolman
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: ca-lan
spec:
  ingressClassName: traefik
  rules:
  - host: spoolman.lan
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: spoolman-service
            port:
              number: 7912
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spoolman-service
            port:
              number: 7912
---
# Added for mainsail 3d printer websocket requirement
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: spoolman-ingress-route
  namespace: spoolman
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: ca-lan
  routes:
    - match: Host(`spoolman.lan`)
      kind: Rule
      services:
        - name: spoolman-service
          port: 7912