apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: spoolman
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QukA7mrrnaA73lOrNKeqBw==,iv:iq7kYSz2FGArGTXjYj4/1Xn7RknDowvrzwgq6awO7SI=,tag:9BQ+03cua6DG/NI0jdnIXA==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRTAweW8xUmljS0plRnpV
            WFI5WlgySmtKVXJWNVdwd3VLS0ZGcWJYRERrClFBSnltMUM3cFMvTTNSOGFuK2VP
            VFlXSU05cTVtOGZtSmhIQWl3NWVrMkUKLS0tIHltVjA2aGNDdGQyMmIxOEozQzlm
            U1VyRGtOcURTWHpIN0l0a2hDN0dXcTAKdTP1sJCpQRVX0aFSquN/icqfaEZ9E4Cw
            C5EmeN1QIQsP92k/H/HiNL/3Uq+xCA2DPfHvS9p7dVfg+dy+VzHh+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T07:19:43Z"
    mac: ENC[AES256_GCM,data:srSJSdagXQzBaUAA1vDDX2kqyHDm761UvcWTQHoNk6X/yuVzdJO3gda2blAlTh8VLXiWX+R26viGmgfXDupumOAtW82tSpL7HhDiYle6/GiHSCa/cMBz6+IVxmTncnVYqomJWAdPRZlYr3Xw8fuBheu2SyxLVEH+LNKXR00L4v0=,iv:0/aOyvC2wdtwn6VVhrp8zVd2MbXuKy/kmxF0LmqgipA=,tag:nBGvYUiilxLqs+Ue4QlnSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
