apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:fhkx/4CMFMAiyR2SCMBljSQTDhA=,iv:gZs8vHQoP4H0OELRfbp5cILI8FkIXhqq1nsy9n2gux4=,tag:Rwj61fy3r+rsU268r7kBlA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:YNJ80ltT92bQQQw46Pdt9FVqGjSMMKXmdA3sJaKib1OATxJLcy/eXg==,iv:1MabQs4XG/EdeLLVhqg6R+Tpdc4AIG76/F28IUNmlgw=,tag:LufcR+yMBvbTBXDCoKnSuA==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNEJhTldiZURqOUMrUmls
            UUxGUk5SYUFUQ3lnVUlsb1JLZ1N6ZTRvUVRZClZWVEZSY053MHhGeTBaZG42VENk
            aHgxWDJIczl2V2NsMU42SlQzTnBBLzQKLS0tIDBLd1FadHRMd3FUZHA5Q1JLTWJW
            NEsxN3NtNGUvMjFCaFVVdXhpVy94M2cKJZqGQHQyrDPYQMU6RXGuh8l1ey7ZzgZO
            doJ524hYdz5Qim75yPq+D71avLGk/u8vHy+y4MlFgyeytMr9ELfGDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T12:38:01Z"
    mac: ENC[AES256_GCM,data:7JZSGan5CTINy6x8yCRwD+FE/SYCZ4YBHUkHPmwvRnBDujf3/UgwZEbafJ8dyQEhnh8MIH2oZJ3wdaT6EETN233LQqFEzSiuf7lLIlKNtRrViT42dGrvHwNlq2fLIgKtOAu3zM5XrLuqHZF9cSG+h6HikHH1K2yGP9/vc0ip5S8=,iv:/jWUV3pgX23a/aPk5AgLWzdjH6Kkm4gkknjWaXSYYtk=,tag:Gr5rL9bTTTBU8s+F68ZRBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
