apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:HPoBC4uCFvSkkz0Z0rRaDCsPBys=,iv:F4Dz5rpRWYM13NaFUhUXNEMRdFmMqdRDQanFIYO2sJw=,tag:lGz8dnQucxkevrTkZuz8HQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:BvibhCQ6mbfartD7Cz22n3POvfzcrh7xr2yqcVvHSDl3dRQOnvLqKw==,iv:uAVBOXDhcABBsS5VfzJcOAoA/IGJELpr+wZ+V6UgZ3U=,tag:EcEZFJBt1t+1X63pEsNHYg==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdmw0blVudUszRGd4Zkla
            cWdZQjhvaWh6aUhTRnZ1UENLN0Q2N1pVU1NrCjdCL1J6cTVXWVhaTUo2RHRnUTMr
            R2pTcW1BNENDNzU1L1BaMlR0aDR0ZzgKLS0tIGRrU1VBUGI0YzBhZkI3MUhPY01F
            dnkwZmp4YkRLanZiRkJ6eTJ1dDkwN2sKr1GmqYpMt01owIsuSO0qlSaEpl14zR9X
            Xp8wFErb4SlVqAiAZs2hj6aqQ48CyXb9/WDOIXKKc/Z75tN8D9RvSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T06:04:52Z"
    mac: ENC[AES256_GCM,data:ZOnJoj1Tocobd6mdT9kpO1fN2r2wgbigNWQaFxllkKIRQy3hGlSxr7f/7MpKi5i5qllqpfjMio1TwD9D5/mZ9xbEVbwrgmEn4wV88R0Z2x/1/HDcGHZVSulsFMsAVGGqMfogYWjYwrFPQ3bMJOXAVu4+CYhSDKLDKPuh3EmXsFs=,iv:UvGMImxnj5C2uC0XfuDy/LmewFAn1oxOQCwAz5peO0k=,tag:eKSitYWMH6ISuN7GHa2pLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
