apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:/C8IGCgNydubIl29DWWOj7jVh1o=,iv:gNjIMW11PVg6EXo1lSwGNVqniJ9GFVWf5O/K0NdH1Ps=,tag:iIWfN1UhVrod7Po7xyWhsA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:vr1/+NHzkERgB8J7096FIuBNPqF/EzhmdmZlaPX0lZMPe1ewEDrplg==,iv:sYOYqamniQJ5ExCCSUaebzJ2I5clY87rlLwXBe3kMSc=,tag:0Iict1bqvt0PN1YolIY93A==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT0JTbDMxMnFzR2dvOStl
            eHpUS1FWNWIyYnNRUFpaenhJYi9uT2h0ZHhvCjB3NE9jVEdzcFVXVThpTzhYQkFu
            OHBBVzZSYTgzdzlSRUNTZCtwempkTFUKLS0tIFVFeFBNUXAzTndVaEk0dzBGU1Jh
            ZDFxOTJDam1FT2xLSFZTQnlPWFhjdnMKZhGDIYIQqmcUMhitLXQ6/35fpC8Kibdy
            fo2KiqSyx15p4sGrTW7BrdPrn+Ogtm3ssFW6SK1rQ9KdrJUfGQYPWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T12:40:54Z"
    mac: ENC[AES256_GCM,data:Z2UiSsQht8ynl4RQHWgT8RvNqu6uE4b1jf+aIcm5XnwDt1nOnfpoC6AJJkz42a0j3KY3Qe+6IgdYpIPnvszlhVkjE3iaRlLelfYN7tnG3Bf3vsgwfkpRF3gL6vY97jFwI4Nn4peagZgerKOUhAqImwSylwcJLllJl5HJoJmqBRA=,iv:r54w+C3EYmssAimzYj7VERDS4ZK11M2DZ7xbCvFiCBg=,tag:Q98Lda6mABAg2snCA/taBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
